import type { Metadata } from "next";
import ThemeRegistry from "../shared/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body>
              <ThemeRegistry>
                  {children }
              </ThemeRegistry>
        </body>
    </html>
  );
}
